### ISSUE TITLE
 raise ValueError("empty vocabulary; perhaps the documents only" ValueError: empty vocabulary; perhaps the documents only contain stop words

### ISSUE THREAD

**Issue by hariprasadgns** [javierhonduco/emoji-prediction#4]
harigns@harigns:~/emoji-prediction-master/classify$ python3 sklearn_experiments.py 10000
total_tweets=10000 total_training=8000 diff_emojis=0
Traceback (most recent call last):
  File "sklearn_experiments.py", line 151, in <module>
    learn_with(SGDClassifier, dataset=dataset)
  File "sklearn_experiments.py", line 97, in learn_with
    X = vectorizer.fit_transform(data)
  File "/home/harigns/anaconda3/lib/python3.7/site-packages/sklearn/feature_extraction/text.py", line 1603, in fit_transform
    X = super(TfidfVectorizer, self).fit_transform(raw_documents)
  File "/home/harigns/anaconda3/lib/python3.7/site-packages/sklearn/feature_extraction/text.py", line 1032, in fit_transform
    self.fixed_vocabulary_)
  File "/home/harigns/anaconda3/lib/python3.7/site-packages/sklearn/feature_extraction/text.py", line 961, in _count_vocab
    raise ValueError("empty vocabulary; perhaps the documents only"
ValueError: empty vocabulary; perhaps the documents only contain stop words

I'm getting the above error . So please help me to solve this.

**Comment by javierhonduco** [comment]
Seems that this happens when you have only one string rather than a list of strings: https://stackoverflow.com/questions/20928769/python-tfidfvectorizer-throwing-empty-vocabulary-perhaps-the-documents-only-c
